version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Asia/Tokyo
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Asia/Tokyo
