name: docker-build

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Transform GitHub Actions metadata to Docker image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          build-args: VERSION=${{ steps.meta.outputs.version }}
